import os
from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch_ros.actions import Node
from launch.actions import IncludeLaunchDescription
from launch.launch_description_sources import PythonLaunchDescriptionSource


def generate_launch_description():
    config_dir = os.path.join(get_package_share_directory('amr'),'config')
    # world_dir = os.path.join(get_package_share_directory('amr'),'worlds')
    map_file = os.path.join(config_dir,'map_1.yaml') #Add the path of map generated by cartographer package
    param_file = os.path.join(config_dir,'nav2_params.yaml')
    rviz_config_dir = os.path.join(config_dir,'navigation.rviz')
    # world_file = os.path.join(world_dir,'world_1')

    return LaunchDescription([
        IncludeLaunchDescription(
            PythonLaunchDescriptionSource([get_package_share_directory('nav2_bringup'),'/launch','/bringup_launch.py']),
            launch_arguments={
            'map':map_file,
            'params_file': param_file}.items()
        ),


    Node(
        package='rviz2',
        executable='rviz2',
        name='rviz2_node',
        arguments=['-d', rviz_config_dir],
        output='screen'
        )
    ])
